### ISSUE TITLE
[BUG] Плохо работает с Aspro.MAX

### ISSUE THREAD

**Issue by zdv1g** [darkfriend/dev2fun.imagecompress#13]
Стоял 20 дней, насобирал кеша на 600 гигов (очистка работает).
![image](https://github.com/darkfriend/dev2fun.imagecompress/assets/8127249/06ad2dd4-a637-405a-a9b8-f9186c1850e4)

**Comment by darkfriend** [comment]
Здравствуйте.
Спасибо за обращение!

Убедитесь, что интервальные агенты выполняются на кроне или добавьте скрипт `console/cache-delayed-delete.php -l=10000` в крон.
Если не помогло, то переоткройте issue.
