### ISSUE TITLE
Дублирование "Страницы исключения:" при сохранении настроек

### ISSUE THREAD

**Issue by AndreyChursin** [darkfriend/dev2fun.imagecompress#14]
При любом сохранении настроек модуля поле "Страницы исключения:" из раздела "Настройки конвертации webp/avif" увеличивается на одно пустое правило (предыдущее пустое заполняется строкой вида: "#(\/bitrix\/.*)#")

**Comment by darkfriend** [comment]
Здравствуйте.
Спасибо за обращение.

Если я вас правильно понял, то вы хотите, чтоб в поле не заполнялась регулярка, которая идет по умолчанию.\
Если это сделать, то страницы исключений будут не очевидны. Цель была как раз указать, что данное правильно работает по умолчанию.

**Comment by AndreyChursin** [comment]
Извиняюсь, действительно апдейта не было... после 0.7.4 все ок
