### ISSUE TITLE
Не работает при запросах на контроллеры БУС

### ISSUE THREAD

**Issue by AndreyChursin** [darkfriend/dev2fun.imagecompress#15]
Проблема: при запросах на контроллеры БУС "/bitrix/services/main/ajax.php" обработчики модуля не срабатывают из-за исключения по умолчанию:

<img width="548" alt="image" src="https://github.com/darkfriend/dev2fun.imagecompress/assets/11028058/5019172b-f993-4456-8d2f-9f0d09f3ec93">

Для решения проблемы можно заменить дефолтную регулярку на 
`#(\/bitrix\/(?!services\/main\/ajax\.php).*)#`

Либо добавить настройку для включения путей по регулярке, тогда в методе 
`Dev2fun\ImageCompress\Convert::isExcludePage`

нужно сначала проверить путь на включение.

**Comment by darkfriend** [comment]
Здравствуйте.
Спасибо за обращение.

Спасибо, поправил, в методе `Dev2fun\ImageCompress\Convert::isExcludePage()`, старая регулярка удалится при обновлении.
Изменение появится в версии `0.10.0`
