### ISSUE TITLE
convertImageByPath->process не может конвертировать файл находящийся в /upload/...

### ISSUE THREAD

**Issue by AndreyChursin** [darkfriend/dev2fun.imagecompress#16]
Для обхода проблемы с конвертированием картинок в ответах контроллеров пробовал конвертировать изображения с помощью класса Dev2fun\ImageCompress\Convert
Но при вызове 
`(new Dev2fun\ImageCompress\Convert)->convertImageByPath('/upload/....jpg')`
в методе
`Dev2fun\ImageCompress\Convert::process`
при проверке путей для конвертации идет генерация пути и проверка наличия файла по этому пути: "/upload//upload/...." но такого пути **нет** поэтому конвертация не происходит.
```php
        $upload_dir = Option::get('main', 'upload_dir', 'upload');
        $res = "/$upload_dir/{$arFile["SUBDIR"]}/{$arFile["FILE_NAME"]}";

```

**Comment by darkfriend** [comment]
Здравствуйте.
Спасибо за обращение!

Проблему понял, добавил ключ `hasFullPath` в `$options` внутри метода `Convert::convertImageByPath()` и поддержку в `Convert::process()`.
Изменение появится в версии `0.10.0`.
