### ISSUE TITLE
Apple картинки

### ISSUE THREAD

**Issue by dominikes** [darkfriend/dev2fun.imagecompress#3]
Версия 0.5.2, на apple устройствах некоторые картинки по прежнему не отображаются, если активируется модуль webp

**Comment by darkfriend** [comment]
Здравствуйте.
Спасибо за обращение.

Проблема была на некоторых картинках, обновитесь, пожалуйста, до версии 0.5.3
Не забудьте последовательно применить миграции из migrations.

**Comment by darkfriend** [comment]
Если проблема сохраниться, пожалуйста, напишите в support@dev2fun.com со ссылкой на проблемную страницу и доступами к админке, чтоб я смог понять что именно мешает картинке отобразиться.
