### ISSUE TITLE
Использовать PATH для поиска утилит

### ISSUE THREAD

**Issue by nradchenko** [darkfriend/dev2fun.imagecompress#6]
Сейчас модуль по умолчанию предполагает, что утилиты optipng, jpegoptim и так далее установлены в директории `/usr/bin`.

Исходя из такого значения по умолчанию я полагаю, что ваш модуль в первую очередь ориентирован на Unix-системы. В таких системах обозначенная директория не является единственным местом хранения исполняемых файлов "по умолчанию", и, согласно POSIX, список таких директорий указывается в переменной окружения PATH.

Использование в качестве умолчания `/usr/bin` препятствует обнаружению утилит, установленных в директориях типа `/usr/local/bin`, которые де-факто являются приоритетными, либо установленных в любых других директориях, выбранных администратором и заданных им в переменной PATH.

Предлагаю по умолчанию явно не передавать функции `exec` путь к утилитам в том случае, если он не был задан пользователем, позволяя функции и системе самостоятельно попытаться найти исполняемый файл стандартным способом - согласно значению PATH.

**Comment by darkfriend** [comment]
Здравствуйте.
Спасибо за идею.

Но лучше использовать полный путь, чтоб избежать возможных проблем.
