### ISSUE TITLE
Не рабочая конвертация в версии 0.7.2

### ISSUE THREAD

**Issue by kruvas** [darkfriend/dev2fun.imagecompress#7]
в последней версии в файле /lib/Convert.php 
добавили $globalEnable. и сеттер геттер для него. но нигде их не используете.
а так как по дефолту там false, то конвертация не работает.

**Comment by darkfriend** [comment]
Здравствуйте.
Спасибо, что сообщили!

Поправил в версии [0.7.3](https://github.com/darkfriend/dev2fun.imagecompress/releases/tag/0.7.3)
